services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:v2
    container_name: arcane
    ports:
      - "3552:3552"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./builds:/builds
      - ./backups:/backups
      - ../:/app/data/projects
    environment:
      APP_URL: ${APP_URL}
      PUID: "1000"
      PGID: "1000"
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped
