services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    ports:
      - 4000:80
    command:
      - serve
    volumes:
      - ./ntfy-data/cache:/var/cache/ntfy
      - ./ntfy-data/cache/attachments:/var/cache/ntfy/attachments
      - ./ntfy-data/lib:/var/lib/ntfy
      - ./ntfy-data/etc:/etc/ntfy

# server.yml - located in ./ntfy-data/etc/
# Server
# base-url: "https://ntfy.tailda5058.ts.net"

# Access control
# auth-file: "/var/lib/ntfy/auth.db"
# auth-default-access: "deny-all"
# auth-users:
#   - "admin-user:.......:admin"
# enable-login: true
# require-login: true

# Attachments
# attachment-cache-dir: "/var/cache/ntfy/attachments"
# attachment-total-size-limit: "1G"
# attachment-expiry-duration: "1h"

# Message cache
# cache-file: "/var/cache/ntfy/cache.db"

# Upstream
# upstream-base-url: "https://ntfy.sh"
