services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    ports:
      - 4000:80
    command:
      - serve
    volumes:
      - ./ntfy-data/cache:/var/cache/ntfy
      - ./ntfy-data/cache/attachments:/var/cache/ntfy/attachments
      - ./ntfy-data/lib:/var/lib/ntfy
      - ./ntfy-data/etc:/etc/ntfy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://localhost:4000/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    init: true # needed, if healthcheck is used. Prevents zombie processes


# server.yml - located in ./ntfy-data/etc/
# Server
# base-url: "https://ntfy.tailda5058.ts.net"

# Access control
# auth-file: "/var/lib/ntfy/auth.db"
# auth-default-access: "deny-all"
# auth-users:
#   - "admin-user:.......:admin"
# enable-login: true
# require-login: true

# Attachments
# attachment-cache-dir: "/var/cache/ntfy/attachments"
# attachment-total-size-limit: "1G"
# attachment-expiry-duration: "1h"

# Message cache
# cache-file: "/var/cache/ntfy/cache.db"

# Upstream
# upstream-base-url: "https://ntfy.sh"
