# To make use of the reverse proxy the other services need the following:
# environment:
#   - VIRTUAL_HOST: "URL.COM,SUB.URL.COM"
#   - LETSENCRYPT_HOST: "URL.COM,SUB.URL.COM"
# networks:
#   - web
# networks:
#   web:
#      external: true

services:
  reverse-proxy:
    image: jwilder/nginx-proxy
    container_name: reverse-proxy
    volumes:
      - /etc/nginx/vhost.d
      - /etc/nginx/certs
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./compression.conf:/etc/nginx/conf.d/compression.conf:ro
    restart: unless-stopped
    networks:
      - web
    ports:
      - 80:80
      - 443:443

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-helper
    volumes_from:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=reverse-proxy
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: unless-stopped
    depends_on:
      - reverse-proxy
    networks:
      - web

volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  web:
    external: true
